<?php

module_load_include('inc', 'reports', 'inc/reports.common');

function reports_menu() {
    $items['show'] = array(
        'page callback' => 'showTodayReports',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    );
    $items['report'] = array(
        'page callback' => 'menufun_add_report',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    );
    $items['view'] = array(
        'page callback' => 'menufun_view_report',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    );
	$items['viewbots'] = array(
        'page callback' => 'menufun_view_bots',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    );
	$items['setpath'] = array(
        'page callback' => 'menufun_set_path',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    );
    $items['add'] = array(
        'page callback' => 'menufun_add',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    );
    $items['remove'] = array(
        'page callback' => 'menufun_remove',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    );
    $items['generate'] = array(
        'page callback' => 'menufun_generate',
        'access callback' => 'report_admin_access',
        'type' => MENU_CALLBACK,
    );   
	$items['bots'] = array(
        'page callback' => 'menufun_handler',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    ); 
	$items['managebots'] = array(
        'page callback' => 'menufun_managebots',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    ); 
	$items['displayfiles'] = array(
        'page callback' => 'displayfiles',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    ); 
	$items['scan'] = array(
        'page callback' => 'menufun_scan',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    );	
	$items['path'] = array(
        'page callback' => 'menufun_path_js',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    );
	$items['sectors'] = array(
        'page callback' => 'menufun_load_sectors',
        'access callback' => 'report_user_access',
        'type' => MENU_CALLBACK,
    );

    $items['uploadify'] = array(
        'page callback' => 'menufun_upload',
        //'access callback' => 'report_user_access',
        'access callback' => true,
        'type' => MENU_CALLBACK,
    );
    $items['deploy'] = array(
        'page callback' => 'menufun_deploy',
        'access callback' => 'report_admin_access',
        'type' => MENU_CALLBACK,
    );   

	/*
	$items['admin/settings/report'] = array(
		'title' => 'ITG Report Settings',
		'description' => 'Change how ITG Bots behave.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('reports_admin_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'reports.admin.inc',
	);
	*/
    return $items;
}

function menufun_deploy(){
	module_load_include('inc', 'reports', 'inc/reports.deploy');
	return deploy();
}

function menufun_upload(){
	module_load_include('inc', 'reports', 'inc/reports.upload');
}

function menufun_load_sectors(){
	module_load_include('inc', 'reports', 'inc/reports.sectors');
}

function menufun_path_js(){
	$sector_id = $_REQUEST['sid'];
	$sql = "SELECT * FROM mj_sectors_paths WHERE sps_sct_id = $sector_id";
	$data = db_query($sql);
	$output = array();
	while ($row = db_fetch_object($data)){
		$val = $row->sps_path . ';';
		//$val = str_replace("\\\\", "\\", $val);
		$output[] = $val;
	}
	drupal_json($output);
}

function menufun_set_path(){
	module_load_include('inc', 'reports', 'inc/reports.setpath');
	return set_path();
}

function menufun_remove(){
	module_load_include('inc', 'reports', 'inc/reports.del_report');
}

function menufun_add(){
	module_load_include('inc', 'reports', 'inc/reports.add');
}

function menufun_add_report(){
	module_load_include('inc', 'reports', 'inc/reports.add_report');
	return add_report();
}

function menufun_view_report(){
	module_load_include('inc', 'reports', 'inc/reports.viewreports');
	return view_reports();
}

function menufun_view_bots(){
	module_load_include('inc', 'reports', 'inc/reports.view');
	return view_report();
}

function menufun_generate(){
	module_load_include('inc', 'reports', 'inc/reports.reports');
	return get_reports();
}

function menufun_handler(){
	module_load_include('inc', 'reports', 'inc/reports.view');
	echo get_data();
	exit();
}

function menufun_scan(){
	module_load_include('inc', 'reports', 'inc/reports.scan');
}

function menufun_managebots(){
	module_load_include('inc', 'reports', 'inc/reports.bots');
	return manage_bots();
}